# Generated by Django 4.2.9 on 2024-04-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='LOW', max_length=20),
        ),
    ]
