# Generated by Django 4.2.9 on 2024-04-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
