# Generated by Django 4.2.9 on 2024-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0003_task_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
