# Generated by Django 4.2.9 on 2024-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl_app', '0004_alter_task_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
